"""added created,updated

Revision ID: 50c83186e8b8
Revises: 0d3c15d371cb
Create Date: 2026-06-14 02:04:19.380495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c83186e8b8'
down_revision: Union[str, Sequence[str], None] = '0d3c15d371cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('collections', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('notes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'created_at')
    op.drop_column('collections', 'updated_at')
    op.drop_column('collections', 'created_at')
    # ### end Alembic commands ###
