"""added status column

Revision ID: 71c2a2c48b50
Revises: 198a62571fcf
Create Date: 2026-06-14 21:09:19.250128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c2a2c48b50'
down_revision: Union[str, Sequence[str], None] = '198a62571fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.String(length=20), nullable=False))
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
