"""added i_deleted column

Revision ID: f7ddcca7db1a
Revises: 71c2a2c48b50
Create Date: 2026-06-16 01:08:04.634847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ddcca7db1a'
down_revision: Union[str, Sequence[str], None] = '71c2a2c48b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_archived', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    op.add_column('notes', sa.Column('is_deleted', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    op.add_column('notes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'deleted_at')
    op.drop_column('notes', 'is_deleted')
    op.drop_column('notes', 'is_archived')
    # ### end Alembic commands ###
